version: '2'
services:
    web:
        build: .
        command: sh -c "rake db:migrate && rm -f tmp/pids/server.pid && exec bundle exec rails server -b '0.0.0.0'"
        volumes:
            - .:/notebook-ai
        ports:
            - "3000:3000"
