---
# The authentication token for the application.
# I think this is actually ignored if the ENV var is set, but this is fine for reference / dummy data.
authentication: ENV['SKYLIGHT_AUTHENTICATION']
