
:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: other_names
      :label: Other Names
    - :name: universe_id
      :label: Universe
:appearance:
  :label: Appearance
  :icon: accessibility
  :attributes:
    - :name: physical_description
      :label: Physical Description
    - :name: height
      :label: Height
    - :name: weight
      :label: Weight
:family:
  :label: Family
  :icon: supervisor_account
  :attributes:
    - :name: character_parents
      :label: Parents
    - :name: character_partners
      :label: Partners
    - :name: character_children
      :label: Children
    - :name: deity_parents
      :label: Parents
    - :name: deity_partners
      :label: Partners
    - :name: deity_children
      :label: Children
:symbolism:
  :label: Symbolism
  :icon: thumbs_up_down
  :attributes:
    - :name: symbols
      :label: Symbols
    - :name: elements
      :label: Elements
    - :name: creatures
      :label: Creatures
    - :name: floras
      :label: Floras
    - :name: religions
      :label: Religions
    - :name: relics
      :label: Relics
:powers:
  :label: Powers
  :icon: grade
  :attributes:
    - :name: strengths
      :label: Strengths
    - :name: weaknesses
      :label: Weaknesses
    - :name: abilities
      :label: Abilities
:rituals:
  :label: Rituals
  :icon: import_contacts
  :attributes:
    - :name: prayers
      :label: Prayers
    - :name: rituals
      :label: Rituals
    - :name: human_interaction
      :label: Human Interaction
    - :name: related_towns
      :label: Related towns
    - :name: related_landmarks
      :label: Related landmarks
:history:
  :label: History
  :icon: timeline
  :attributes:
    - :name: notable_events
      :label: Notable Events
    - :name: family_history
      :label: Family History
    - :name: life_story
      :label: Life Story
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
