
:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: other_names
      :label: Other Names
:appearance:
  :label: Appearance
  :icon: face
  :attributes:
    - :name: physical_description
      :label: Physical Description
    - :name: height
      :label: Height
    - :name: weight
      :label: Weight
:symbolism:
  :label: Symbolism
  :icon: info
  :attributes:
    - :name: symbols
      :label: Symbols
    - :name: elements
      :label: Elements
:powers:
  :label: Powers
  :icon: info
  :attributes:
    - :name: strengths
      :label: Strengths
    - :name: weaknesses
      :label: Weaknesses
:rituals:
  :label: Rituals
  :icon: info
  :attributes:
    - :name: prayers
      :label: Prayers
    - :name: rituals
      :label: Rituals
    - :name: human_interaction
      :label: Human Interaction
:history:
  :label: History
  :icon: face
  :attributes:
    - :name: notable_events
      :label: Notable Events
    - :name: family_history
      :label: Family History
    - :name: life_story
      :label: Life Story
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
