
:overview:
  :label: Overview
  :icon: info
  :attributes:
    [:name, :description, :other_names, :physical_description, :height, :weight, :symbols, :elements, :strengths, :weaknesses, :prayers, :rituals, :human_interaction, :notable_events, :family_history, :life_story, :notes, :private_notes, :privacy, :universe_id]
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
    