
:overview:
  :label: Overview
  :icon: info
  :attributes:
    [:name, :description, :type_of_government, :power_structure, :power_source, :checks_and_balances, :sociopolitical, :socioeconomical, :geocultural, :laws, :immigration, :privacy_ideologies, :electoral_process, :term_lengths, :criminal_system, :approval_ratings, :military, :navy, :airforce, :space_program, :international_relations, :civilian_life, :founding_story, :flag_design_story, :notable_wars, :notes, :private_notes, :privacy, :universe_id]
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
    