
:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: size
      :label: Size
    - :name: surface
      :label: Surface
    - :name: landmarks
      :label: Landmarks
    - :name: climate
      :label: Climate
    - :name: weather
      :label: Weather
    - :name: water_content
      :label: Water Content
    - :name: natural_resources
      :label: Natural Resources
    - :name: length_of_day
      :label: Length Of Day
    - :name: length_of_night
      :label: Length Of Night
    - :name: calendar_system
      :label: Calendar System
    - :name: population
      :label: Population
    - :name: moons
      :label: Moons
    - :name: orbit
      :label: Orbit
    - :name: visible_constellations
      :label: Visible Constellations
    - :name: first_inhabitants_story
      :label: First Inhabitants Story
    - :name: world_history
      :label: World History
    - :name: private_notes
      :label: Private Notes
    - :name: privacy
      :label: Privacy
    - :name: universe_id
      :label: Universe
    - :name: notes
      :label: Notes
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
    