
:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: universe_id
      :label: Universe
:geography:
  :label: Geography
  :icon: layers
  :attributes:
    - :name: size
      :label: Size
    - :name: surface
      :label: Surface
    - :name: climate
      :label: Climate
    - :name: weather
      :label: Weather
    - :name: water_content
      :label: Water Content
    - :name: natural_resources
      :label: Natural Resources
    - :name: landmarks
      :label: Landmarks
    - :name: locations
      :label: Locations
    - :name: countries
      :label: Countries
:time:
  :label: Time
  :icon: hourglass_empty
  :attributes:
    - :name: length_of_day
      :label: Length Of Day
    - :name: length_of_night
      :label: Length Of Night
    - :name: calendar_system
      :label: Calendar System
:inhabitants:
  :label: Inhabitants
  :icon: face
  :attributes:
    - :name: population
      :label: Population
    - :name: races
      :label: Races
    - :name: floras
      :label: Flora
    - :name: creatures
      :label: Creatures
    - :name: religions
      :label: Religions
    - :name: deities
      :label: Deities
    - :name: groups
      :label: Groups
    - :name: languages
      :label: Languages
    - :name: towns
      :label: Towns
:astral:
  :label: Astral
  :icon: star_border
  :attributes:
    - :name: moons
      :label: Moons
    - :name: orbit
      :label: Orbit
    - :name: visible_constellations
      :label: Visible Constellations
    - :name: nearby_planets
      :label: Nearby planets
:history:
  :label: History
  :icon: timeline
  :attributes:
    - :name: first_inhabitants_story
      :label: First Inhabitants Story
    - :name: world_history
      :label: World History
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
