
:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: other_names
      :label: Other Names
    - :name: materials
      :label: Materials
    - :name: manufacturing_process
      :label: Manufacturing Process
    - :name: sales_process
      :label: Sales Process
    - :name: cost
      :label: Cost
    - :name: rarity
      :label: Rarity
    - :name: purpose
      :label: Purpose
    - :name: how_it_works
      :label: How It Works
    - :name: resources_used
      :label: Resources Used
    - :name: physical_description
      :label: Physical Description
    - :name: size
      :label: Size
    - :name: weight
      :label: Weight
    - :name: colors
      :label: Colors
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
    - :name: privacy
      :label: Privacy
    - :name: universe_id
      :label: Universe
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private Notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
    